FROM node:20-alpine as build

WORKDIR /app

COPY package*.json ./
RUN npm install @vitejs/plugin-react

COPY . .
RUN npm run build

FROM nginx:alpine

COPY --from=build /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

RUN chmod -R 755 /usr/share/nginx/html


EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]