version: '3.9'

services:
  database:
    build:
      context: ./database
      dockerfile: Dockerfile
    container_name: grepmind-db
    restart: unless-stopped
    env_file:
      - ./database/.env
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: grepmind-backend
    restart: unless-stopped
    env_file:
      - ./backend/.env
    depends_on:
      - database
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    command: ["node", "--watch", "server.js"]

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: grepmind-frontend
    restart: unless-stopped
    env_file:
      - ./frontend/.env
    depends_on:
      - backend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev"]

volumes:
  db_data:
